# Generated by Django 5.0.4 on 2024-04-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='back',
            new_name='backgroundImage',
        ),
    ]
