# Generated by Django 5.0.4 on 2024-04-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='from_email',
            new_name='email',
        ),
    ]
